# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v14.40.2
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey_client
from airkey_client.models.system_protocol_event import SystemProtocolEvent  # noqa: E501
from airkey_client.rest import ApiException


class TestSystemProtocolEvent(unittest.TestCase):
    """SystemProtocolEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemProtocolEvent(self):
        """Test SystemProtocolEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = airkey_client.models.system_protocol_event.SystemProtocolEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
