# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey
from airkey.models.send_registration_code_request import SendRegistrationCodeRequest  # noqa: E501
from airkey.rest import ApiException


class TestSendRegistrationCodeRequest(unittest.TestCase):
    """SendRegistrationCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendRegistrationCodeRequest(self):
        """Test SendRegistrationCodeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = airkey.models.send_registration_code_request.SendRegistrationCodeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
