# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v14.40.2
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey_client
from airkey_client.models.one_day_authorization_info import OneDayAuthorizationInfo  # noqa: E501
from airkey_client.rest import ApiException


class TestOneDayAuthorizationInfo(unittest.TestCase):
    """OneDayAuthorizationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneDayAuthorizationInfo(self):
        """Test OneDayAuthorizationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = airkey_client.models.one_day_authorization_info.OneDayAuthorizationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
