# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v14.40.2
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey_client
from airkey_client.api.holiday_calendars_api import HolidayCalendarsApi  # noqa: E501
from airkey_client.rest import ApiException


class TestHolidayCalendarsApi(unittest.TestCase):
    """HolidayCalendarsApi unit test stubs"""

    def setUp(self):
        self.api = HolidayCalendarsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_holiday_calendar_slot(self):
        """Test case for create_holiday_calendar_slot

        Adds a new holiday calendar slot to the holiday calendar.  # noqa: E501
        """
        pass

    def test_delete_holiday_calendar_slot(self):
        """Test case for delete_holiday_calendar_slot

        Deletes provided holiday calendar slot.  # noqa: E501
        """
        pass

    def test_get_holiday_calendar(self):
        """Test case for get_holiday_calendar

        Gets a specific holiday calendar.  # noqa: E501
        """
        pass

    def test_get_holiday_calendar_slot(self):
        """Test case for get_holiday_calendar_slot

        Gets a specific holiday calendar slot.  # noqa: E501
        """
        pass

    def test_get_holiday_calendars(self):
        """Test case for get_holiday_calendars

        Gets all holiday calendars.  # noqa: E501
        """
        pass

    def test_get_locks_by_calendar_id(self):
        """Test case for get_locks_by_calendar_id

        Gets all locks using the holiday calendar.  # noqa: E501
        """
        pass

    def test_update_holiday_calendar(self):
        """Test case for update_holiday_calendar

        Updates the holiday calendar.  # noqa: E501
        """
        pass

    def test_update_holiday_calendar_slot(self):
        """Test case for update_holiday_calendar_slot

        Updates a holiday calendar slot of the holiday calendar.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
