# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v14.40.2
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey_client
from airkey_client.api.areas_api import AreasApi  # noqa: E501
from airkey_client.rest import ApiException


class TestAreasApi(unittest.TestCase):
    """AreasApi unit test stubs"""

    def setUp(self):
        self.api = AreasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_area(self):
        """Test case for get_area

        Gets a specific area.  # noqa: E501
        """
        pass

    def test_get_areas(self):
        """Test case for get_areas

        Gets all available areas.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
