# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v14.40.2
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import airkey_client
from airkey_client.api.send_a_key_api import SendAKeyApi  # noqa: E501
from airkey_client.rest import ApiException


class TestSendAKeyApi(unittest.TestCase):
    """SendAKeyApi unit test stubs"""

    def setUp(self):
        self.api = SendAKeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send_a_key(self):
        """Test case for send_a_key

        Sends a registration code to the phone and creates all necessary prerequisites if needed.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
