# coding: utf-8

# flake8: noqa

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from airkey.api.areas_api import AreasApi
from airkey.api.authorizations_api import AuthorizationsApi
from airkey.api.blacklists_api import BlacklistsApi
from airkey.api.credits_api import CreditsApi
from airkey.api.customer_api import CustomerApi
from airkey.api.events_api import EventsApi
from airkey.api.holiday_calendars_api import HolidayCalendarsApi
from airkey.api.lock_protocol_api import LockProtocolApi
from airkey.api.locks_api import LocksApi
from airkey.api.maintenance_tasks_api import MaintenanceTasksApi
from airkey.api.media_api import MediaApi
from airkey.api.medium_protocol_api import MediumProtocolApi
from airkey.api.persons_api import PersonsApi
from airkey.api.public_mgmt_api import PublicMgmtApi
from airkey.api.send_a_key_api import SendAKeyApi
from airkey.api.system_protocol_api import SystemProtocolApi
# import ApiClient
from airkey.api_client import ApiClient
from airkey.configuration import Configuration
# import models into sdk package
from airkey.models.app_paired_event_details import AppPairedEventDetails
from airkey.models.area import Area
from airkey.models.area_paging_list import AreaPagingList
from airkey.models.authorization import Authorization
from airkey.models.authorization_change import AuthorizationChange
from airkey.models.authorization_create import AuthorizationCreate
from airkey.models.authorization_delete import AuthorizationDelete
from airkey.models.authorization_info import AuthorizationInfo
from airkey.models.authorization_paging_list import AuthorizationPagingList
from airkey.models.authorization_sync_details import AuthorizationSyncDetails
from airkey.models.authorization_synchronized_event_details import AuthorizationSynchronizedEventDetails
from airkey.models.blacklist_entry import BlacklistEntry
from airkey.models.card import Card
from airkey.models.card_paging_list import CardPagingList
from airkey.models.credit_info import CreditInfo
from airkey.models.customer import Customer
from airkey.models.event import Event
from airkey.models.event_details import EventDetails
from airkey.models.event_paging_list import EventPagingList
from airkey.models.fixed_medium_simple_authorization_create import FixedMediumSimpleAuthorizationCreate
from airkey.models.holiday_calendar import HolidayCalendar
from airkey.models.holiday_calendar_list import HolidayCalendarList
from airkey.models.holiday_calendar_series import HolidayCalendarSeries
from airkey.models.holiday_calendar_series_create import HolidayCalendarSeriesCreate
from airkey.models.holiday_calendar_slot import HolidayCalendarSlot
from airkey.models.holiday_calendar_slot_create import HolidayCalendarSlotCreate
from airkey.models.holiday_calendar_slot_delete import HolidayCalendarSlotDelete
from airkey.models.holiday_calendar_slot_update import HolidayCalendarSlotUpdate
from airkey.models.json_node import JsonNode
from airkey.models.lock import Lock
from airkey.models.lock_door import LockDoor
from airkey.models.lock_firmware import LockFirmware
from airkey.models.lock_maintenance_task import LockMaintenanceTask
from airkey.models.lock_paging_list import LockPagingList
from airkey.models.lock_protocol import LockProtocol
from airkey.models.lock_protocol_details import LockProtocolDetails
from airkey.models.lock_protocol_entry import LockProtocolEntry
from airkey.models.lock_protocol_event import LockProtocolEvent
from airkey.models.lock_protocol_paging_list import LockProtocolPagingList
from airkey.models.maintenance_task_paging_list import MaintenanceTaskPagingList
from airkey.models.medium import Medium
from airkey.models.medium_assignment import MediumAssignment
from airkey.models.medium_paging_list import MediumPagingList
from airkey.models.one_day_authorization_info import OneDayAuthorizationInfo
from airkey.models.periodical_authorization_info import PeriodicalAuthorizationInfo
from airkey.models.periodical_period import PeriodicalPeriod
from airkey.models.permanent_authorization_info import PermanentAuthorizationInfo
from airkey.models.person import Person
from airkey.models.person_create import PersonCreate
from airkey.models.person_paging_list import PersonPagingList
from airkey.models.phone import Phone
from airkey.models.phone_create import PhoneCreate
from airkey.models.phone_paging_list import PhonePagingList
from airkey.models.phone_settings import PhoneSettings
from airkey.models.send_a_key_phone import SendAKeyPhone
from airkey.models.send_a_key_request import SendAKeyRequest
from airkey.models.send_a_key_response import SendAKeyResponse
from airkey.models.send_registration_code_request import SendRegistrationCodeRequest
from airkey.models.simple_area import SimpleArea
from airkey.models.simple_authorization_create import SimpleAuthorizationCreate
from airkey.models.simple_authorization_info import SimpleAuthorizationInfo
from airkey.models.simple_lock import SimpleLock
from airkey.models.simple_medium import SimpleMedium
from airkey.models.system_protocol import SystemProtocol
from airkey.models.system_protocol_details import SystemProtocolDetails
from airkey.models.system_protocol_entry import SystemProtocolEntry
from airkey.models.system_protocol_event import SystemProtocolEvent
from airkey.models.system_protocol_paging_list import SystemProtocolPagingList
from airkey.models.unlocking_event_details import UnlockingEventDetails
