# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from airkey.models.event_details import EventDetails  # noqa: F401,E501

class AuthorizationSynchronizedEventDetails(EventDetails):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'medium_id': 'int',
        'synced_authorization_list': 'list[AuthorizationSyncDetails]'
    }
    if hasattr(EventDetails, "swagger_types"):
        swagger_types.update(EventDetails.swagger_types)

    attribute_map = {
        'medium_id': 'mediumId',
        'synced_authorization_list': 'syncedAuthorizationList'
    }
    if hasattr(EventDetails, "attribute_map"):
        attribute_map.update(EventDetails.attribute_map)

    def __init__(self, medium_id=None, synced_authorization_list=None, *args, **kwargs):  # noqa: E501
        """AuthorizationSynchronizedEventDetails - a model defined in Swagger"""  # noqa: E501
        self._medium_id = None
        self._synced_authorization_list = None
        self.discriminator = None
        if medium_id is not None:
            self.medium_id = medium_id
        if synced_authorization_list is not None:
            self.synced_authorization_list = synced_authorization_list
        EventDetails.__init__(self, *args, **kwargs)

    @property
    def medium_id(self):
        """Gets the medium_id of this AuthorizationSynchronizedEventDetails.  # noqa: E501

        Unique identifier of the synchronized medium  # noqa: E501

        :return: The medium_id of this AuthorizationSynchronizedEventDetails.  # noqa: E501
        :rtype: int
        """
        return self._medium_id

    @medium_id.setter
    def medium_id(self, medium_id):
        """Sets the medium_id of this AuthorizationSynchronizedEventDetails.

        Unique identifier of the synchronized medium  # noqa: E501

        :param medium_id: The medium_id of this AuthorizationSynchronizedEventDetails.  # noqa: E501
        :type: int
        """

        self._medium_id = medium_id

    @property
    def synced_authorization_list(self):
        """Gets the synced_authorization_list of this AuthorizationSynchronizedEventDetails.  # noqa: E501

        List of synchronized authorizations  # noqa: E501

        :return: The synced_authorization_list of this AuthorizationSynchronizedEventDetails.  # noqa: E501
        :rtype: list[AuthorizationSyncDetails]
        """
        return self._synced_authorization_list

    @synced_authorization_list.setter
    def synced_authorization_list(self, synced_authorization_list):
        """Sets the synced_authorization_list of this AuthorizationSynchronizedEventDetails.

        List of synchronized authorizations  # noqa: E501

        :param synced_authorization_list: The synced_authorization_list of this AuthorizationSynchronizedEventDetails.  # noqa: E501
        :type: list[AuthorizationSyncDetails]
        """

        self._synced_authorization_list = synced_authorization_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorizationSynchronizedEventDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizationSynchronizedEventDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
