# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthorizationSyncDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authorization_id': 'int',
        'sync_action': 'str'
    }

    attribute_map = {
        'authorization_id': 'authorizationId',
        'sync_action': 'syncAction'
    }

    def __init__(self, authorization_id=None, sync_action=None):  # noqa: E501
        """AuthorizationSyncDetails - a model defined in Swagger"""  # noqa: E501
        self._authorization_id = None
        self._sync_action = None
        self.discriminator = None
        if authorization_id is not None:
            self.authorization_id = authorization_id
        if sync_action is not None:
            self.sync_action = sync_action

    @property
    def authorization_id(self):
        """Gets the authorization_id of this AuthorizationSyncDetails.  # noqa: E501

        Unique authorization identifier  # noqa: E501

        :return: The authorization_id of this AuthorizationSyncDetails.  # noqa: E501
        :rtype: int
        """
        return self._authorization_id

    @authorization_id.setter
    def authorization_id(self, authorization_id):
        """Sets the authorization_id of this AuthorizationSyncDetails.

        Unique authorization identifier  # noqa: E501

        :param authorization_id: The authorization_id of this AuthorizationSyncDetails.  # noqa: E501
        :type: int
        """

        self._authorization_id = authorization_id

    @property
    def sync_action(self):
        """Gets the sync_action of this AuthorizationSyncDetails.  # noqa: E501

        Type of sync action  # noqa: E501

        :return: The sync_action of this AuthorizationSyncDetails.  # noqa: E501
        :rtype: str
        """
        return self._sync_action

    @sync_action.setter
    def sync_action(self, sync_action):
        """Sets the sync_action of this AuthorizationSyncDetails.

        Type of sync action  # noqa: E501

        :param sync_action: The sync_action of this AuthorizationSyncDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["CREATED", "DELETED"]  # noqa: E501
        if sync_action not in allowed_values:
            raise ValueError(
                "Invalid value for `sync_action` ({0}), must be one of {1}"  # noqa: E501
                .format(sync_action, allowed_values)
            )

        self._sync_action = sync_action

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorizationSyncDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizationSyncDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
