# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HolidayCalendarList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'holiday_calendar_list': 'list[HolidayCalendar]'
    }

    attribute_map = {
        'holiday_calendar_list': 'holidayCalendarList'
    }

    def __init__(self, holiday_calendar_list=None):  # noqa: E501
        """HolidayCalendarList - a model defined in Swagger"""  # noqa: E501
        self._holiday_calendar_list = None
        self.discriminator = None
        if holiday_calendar_list is not None:
            self.holiday_calendar_list = holiday_calendar_list

    @property
    def holiday_calendar_list(self):
        """Gets the holiday_calendar_list of this HolidayCalendarList.  # noqa: E501

        List of holiday calendars defined in the access control system  # noqa: E501

        :return: The holiday_calendar_list of this HolidayCalendarList.  # noqa: E501
        :rtype: list[HolidayCalendar]
        """
        return self._holiday_calendar_list

    @holiday_calendar_list.setter
    def holiday_calendar_list(self, holiday_calendar_list):
        """Sets the holiday_calendar_list of this HolidayCalendarList.

        List of holiday calendars defined in the access control system  # noqa: E501

        :param holiday_calendar_list: The holiday_calendar_list of this HolidayCalendarList.  # noqa: E501
        :type: list[HolidayCalendar]
        """

        self._holiday_calendar_list = holiday_calendar_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HolidayCalendarList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HolidayCalendarList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
