# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Lock(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'version': 'int',
        'lock_type': 'str',
        'lock_technology': 'str',
        'lock_identifier': 'str',
        'locking_system_id': 'int',
        'lock_door': 'LockDoor',
        'lock_firmware': 'LockFirmware',
        'comment': 'str'
    }

    attribute_map = {
        'id': 'id',
        'version': 'version',
        'lock_type': 'lockType',
        'lock_technology': 'lockTechnology',
        'lock_identifier': 'lockIdentifier',
        'locking_system_id': 'lockingSystemId',
        'lock_door': 'lockDoor',
        'lock_firmware': 'lockFirmware',
        'comment': 'comment'
    }

    def __init__(self, id=None, version=None, lock_type=None, lock_technology=None, lock_identifier=None, locking_system_id=None, lock_door=None, lock_firmware=None, comment=None):  # noqa: E501
        """Lock - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._version = None
        self._lock_type = None
        self._lock_technology = None
        self._lock_identifier = None
        self._locking_system_id = None
        self._lock_door = None
        self._lock_firmware = None
        self._comment = None
        self.discriminator = None
        self.id = id
        self.version = version
        if lock_type is not None:
            self.lock_type = lock_type
        if lock_technology is not None:
            self.lock_technology = lock_technology
        if lock_identifier is not None:
            self.lock_identifier = lock_identifier
        if locking_system_id is not None:
            self.locking_system_id = locking_system_id
        self.lock_door = lock_door
        if lock_firmware is not None:
            self.lock_firmware = lock_firmware
        if comment is not None:
            self.comment = comment

    @property
    def id(self):
        """Gets the id of this Lock.  # noqa: E501

        Unique identifier  # noqa: E501

        :return: The id of this Lock.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Lock.

        Unique identifier  # noqa: E501

        :param id: The id of this Lock.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def version(self):
        """Gets the version of this Lock.  # noqa: E501

        Current version number of the lock  # noqa: E501

        :return: The version of this Lock.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Lock.

        Current version number of the lock  # noqa: E501

        :param version: The version of this Lock.  # noqa: E501
        :type: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def lock_type(self):
        """Gets the lock_type of this Lock.  # noqa: E501

        Type of lock  # noqa: E501

        :return: The lock_type of this Lock.  # noqa: E501
        :rtype: str
        """
        return self._lock_type

    @lock_type.setter
    def lock_type(self, lock_type):
        """Sets the lock_type of this Lock.

        Type of lock  # noqa: E501

        :param lock_type: The lock_type of this Lock.  # noqa: E501
        :type: str
        """
        allowed_values = ["CYLINDER", "WALLREADER"]  # noqa: E501
        if lock_type not in allowed_values:
            raise ValueError(
                "Invalid value for `lock_type` ({0}), must be one of {1}"  # noqa: E501
                .format(lock_type, allowed_values)
            )

        self._lock_type = lock_type

    @property
    def lock_technology(self):
        """Gets the lock_technology of this Lock.  # noqa: E501

        Type of lock technology  # noqa: E501

        :return: The lock_technology of this Lock.  # noqa: E501
        :rtype: str
        """
        return self._lock_technology

    @lock_technology.setter
    def lock_technology(self, lock_technology):
        """Sets the lock_technology of this Lock.

        Type of lock technology  # noqa: E501

        :param lock_technology: The lock_technology of this Lock.  # noqa: E501
        :type: str
        """
        allowed_values = ["NFC_ONLY", "NFC_AND_BLE"]  # noqa: E501
        if lock_technology not in allowed_values:
            raise ValueError(
                "Invalid value for `lock_technology` ({0}), must be one of {1}"  # noqa: E501
                .format(lock_technology, allowed_values)
            )

        self._lock_technology = lock_technology

    @property
    def lock_identifier(self):
        """Gets the lock_identifier of this Lock.  # noqa: E501

        Identifier of the lock  # noqa: E501

        :return: The lock_identifier of this Lock.  # noqa: E501
        :rtype: str
        """
        return self._lock_identifier

    @lock_identifier.setter
    def lock_identifier(self, lock_identifier):
        """Sets the lock_identifier of this Lock.

        Identifier of the lock  # noqa: E501

        :param lock_identifier: The lock_identifier of this Lock.  # noqa: E501
        :type: str
        """

        self._lock_identifier = lock_identifier

    @property
    def locking_system_id(self):
        """Gets the locking_system_id of this Lock.  # noqa: E501

        Technical identifier of the lock  # noqa: E501

        :return: The locking_system_id of this Lock.  # noqa: E501
        :rtype: int
        """
        return self._locking_system_id

    @locking_system_id.setter
    def locking_system_id(self, locking_system_id):
        """Sets the locking_system_id of this Lock.

        Technical identifier of the lock  # noqa: E501

        :param locking_system_id: The locking_system_id of this Lock.  # noqa: E501
        :type: int
        """

        self._locking_system_id = locking_system_id

    @property
    def lock_door(self):
        """Gets the lock_door of this Lock.  # noqa: E501


        :return: The lock_door of this Lock.  # noqa: E501
        :rtype: LockDoor
        """
        return self._lock_door

    @lock_door.setter
    def lock_door(self, lock_door):
        """Sets the lock_door of this Lock.


        :param lock_door: The lock_door of this Lock.  # noqa: E501
        :type: LockDoor
        """
        if lock_door is None:
            raise ValueError("Invalid value for `lock_door`, must not be `None`")  # noqa: E501

        self._lock_door = lock_door

    @property
    def lock_firmware(self):
        """Gets the lock_firmware of this Lock.  # noqa: E501


        :return: The lock_firmware of this Lock.  # noqa: E501
        :rtype: LockFirmware
        """
        return self._lock_firmware

    @lock_firmware.setter
    def lock_firmware(self, lock_firmware):
        """Sets the lock_firmware of this Lock.


        :param lock_firmware: The lock_firmware of this Lock.  # noqa: E501
        :type: LockFirmware
        """

        self._lock_firmware = lock_firmware

    @property
    def comment(self):
        """Gets the comment of this Lock.  # noqa: E501

        Comment  # noqa: E501

        :return: The comment of this Lock.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Lock.

        Comment  # noqa: E501

        :param comment: The comment of this Lock.  # noqa: E501
        :type: str
        """

        self._comment = comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Lock, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Lock):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
