# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MediumAssignment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'medium_id': 'int',
        'person_id': 'int'
    }

    attribute_map = {
        'medium_id': 'mediumId',
        'person_id': 'personId'
    }

    def __init__(self, medium_id=None, person_id=None):  # noqa: E501
        """MediumAssignment - a model defined in Swagger"""  # noqa: E501
        self._medium_id = None
        self._person_id = None
        self.discriminator = None
        self.medium_id = medium_id
        self.person_id = person_id

    @property
    def medium_id(self):
        """Gets the medium_id of this MediumAssignment.  # noqa: E501

        Identifier of the medium  # noqa: E501

        :return: The medium_id of this MediumAssignment.  # noqa: E501
        :rtype: int
        """
        return self._medium_id

    @medium_id.setter
    def medium_id(self, medium_id):
        """Sets the medium_id of this MediumAssignment.

        Identifier of the medium  # noqa: E501

        :param medium_id: The medium_id of this MediumAssignment.  # noqa: E501
        :type: int
        """
        if medium_id is None:
            raise ValueError("Invalid value for `medium_id`, must not be `None`")  # noqa: E501

        self._medium_id = medium_id

    @property
    def person_id(self):
        """Gets the person_id of this MediumAssignment.  # noqa: E501

        Identifier of the person  # noqa: E501

        :return: The person_id of this MediumAssignment.  # noqa: E501
        :rtype: int
        """
        return self._person_id

    @person_id.setter
    def person_id(self, person_id):
        """Sets the person_id of this MediumAssignment.

        Identifier of the person  # noqa: E501

        :param person_id: The person_id of this MediumAssignment.  # noqa: E501
        :type: int
        """
        if person_id is None:
            raise ValueError("Invalid value for `person_id`, must not be `None`")  # noqa: E501

        self._person_id = person_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MediumAssignment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediumAssignment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
