# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PeriodicalPeriod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'weekday': 'str',
        'start_time': 'str',
        'end_time': 'str'
    }

    attribute_map = {
        'weekday': 'weekday',
        'start_time': 'startTime',
        'end_time': 'endTime'
    }

    def __init__(self, weekday=None, start_time=None, end_time=None):  # noqa: E501
        """PeriodicalPeriod - a model defined in Swagger"""  # noqa: E501
        self._weekday = None
        self._start_time = None
        self._end_time = None
        self.discriminator = None
        self.weekday = weekday
        self.start_time = start_time
        self.end_time = end_time

    @property
    def weekday(self):
        """Gets the weekday of this PeriodicalPeriod.  # noqa: E501

        Day of the week  # noqa: E501

        :return: The weekday of this PeriodicalPeriod.  # noqa: E501
        :rtype: str
        """
        return self._weekday

    @weekday.setter
    def weekday(self, weekday):
        """Sets the weekday of this PeriodicalPeriod.

        Day of the week  # noqa: E501

        :param weekday: The weekday of this PeriodicalPeriod.  # noqa: E501
        :type: str
        """
        if weekday is None:
            raise ValueError("Invalid value for `weekday`, must not be `None`")  # noqa: E501
        allowed_values = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]  # noqa: E501
        if weekday not in allowed_values:
            raise ValueError(
                "Invalid value for `weekday` ({0}), must be one of {1}"  # noqa: E501
                .format(weekday, allowed_values)
            )

        self._weekday = weekday

    @property
    def start_time(self):
        """Gets the start_time of this PeriodicalPeriod.  # noqa: E501

        Starting time (format: hh:mm)  # noqa: E501

        :return: The start_time of this PeriodicalPeriod.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this PeriodicalPeriod.

        Starting time (format: hh:mm)  # noqa: E501

        :param start_time: The start_time of this PeriodicalPeriod.  # noqa: E501
        :type: str
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this PeriodicalPeriod.  # noqa: E501

        Ending time (format: hh:mm)  # noqa: E501

        :return: The end_time of this PeriodicalPeriod.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this PeriodicalPeriod.

        Ending time (format: hh:mm)  # noqa: E501

        :param end_time: The end_time of this PeriodicalPeriod.  # noqa: E501
        :type: str
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PeriodicalPeriod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeriodicalPeriod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
