# coding: utf-8

"""
    EVVA AirKey Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v16.20.7
    Contact: office-wien@evva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SendAKeyResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'phone': 'Phone',
        'person': 'Person',
        'authorization': 'Authorization'
    }

    attribute_map = {
        'phone': 'phone',
        'person': 'person',
        'authorization': 'authorization'
    }

    def __init__(self, phone=None, person=None, authorization=None):  # noqa: E501
        """SendAKeyResponse - a model defined in Swagger"""  # noqa: E501
        self._phone = None
        self._person = None
        self._authorization = None
        self.discriminator = None
        if phone is not None:
            self.phone = phone
        if person is not None:
            self.person = person
        if authorization is not None:
            self.authorization = authorization

    @property
    def phone(self):
        """Gets the phone of this SendAKeyResponse.  # noqa: E501


        :return: The phone of this SendAKeyResponse.  # noqa: E501
        :rtype: Phone
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this SendAKeyResponse.


        :param phone: The phone of this SendAKeyResponse.  # noqa: E501
        :type: Phone
        """

        self._phone = phone

    @property
    def person(self):
        """Gets the person of this SendAKeyResponse.  # noqa: E501


        :return: The person of this SendAKeyResponse.  # noqa: E501
        :rtype: Person
        """
        return self._person

    @person.setter
    def person(self, person):
        """Sets the person of this SendAKeyResponse.


        :param person: The person of this SendAKeyResponse.  # noqa: E501
        :type: Person
        """

        self._person = person

    @property
    def authorization(self):
        """Gets the authorization of this SendAKeyResponse.  # noqa: E501


        :return: The authorization of this SendAKeyResponse.  # noqa: E501
        :rtype: Authorization
        """
        return self._authorization

    @authorization.setter
    def authorization(self, authorization):
        """Sets the authorization of this SendAKeyResponse.


        :param authorization: The authorization of this SendAKeyResponse.  # noqa: E501
        :type: Authorization
        """

        self._authorization = authorization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SendAKeyResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendAKeyResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
